name: Python Style Check

on: push

jobs:
  pycodestyle:
    name: pycodestyle
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: python -m pip install --upgrade pip
    - name: Python Style Check
      run: |
        pip install pycodestyle
        pycodestyle --ignore="E121,E123,E126,E226,E24,E704,W503,W504,E501" .
